service: nodejs-assignment

custom:
  defaultStage: dev
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    APP_NAME: ${self:service}
    AWS_ACCESS_KEY_ID: id_key
    AWS_SECRET_ACCESS_KEY: access_key
    LOANS_TABLE_NAME: loansTable
    DYNAMODB_REGION: localhost
    DYNAMODB_ENDPOINT: http://localhost:8000

package:
  exclude:
    - .env
    - coverage/**
    - .dynamodb
  include:
    - build/**

plugins:
  - serverless-pseudo-parameters
  - serverless-dynamodb-local
  - serverless-offline

functions:
  createLoans:
    handler: build/loansService/functions/createLoans/index.handler
    package:
      include:
        - build/loansService/functions/createLoans/*
    events:
      - http:
          method: post
          path: /loans

  deleteLoans:
    handler: build/loansService/functions/deleteLoans/index.handler
    package:
      include:
        - build/loansService/functions/deleteLoans/*
    events:
      - http:
          method: delete
          path: /loans/{id}

  getLoans:
    handler: build/loansService/functions/getLoans/index.handler
    package:
      include:
        - build/loansService/functions/getLoans/*
    events:
      - http:
          method: get
          path: /loans

  function4:
    name: function4
    handler: src/app1/functions.function4
    events:
      - http:
          path: /disburse/{id}
          method: get

resources:
  Resources:
    loansTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: loansTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1